export PS1="\n\[$(tput setaf 4)\]\u \[$(tput setaf 6)\]\w \[$(tput setaf 7)\]\\$ \[$(tput setaf 2)\]\n❯ \[$(tput sgr0)\]"
export PATH=/Applications/Postgres.app/Contents/Versions/9.3/bin/:$PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi
eval "$(rbenv init -)"
alias gst='git status'
alias gaa='git add -A .'
alias gd='git diff'
alias gdc='git diff --cached'
alias gpo='git push -u origin master'
alias gcm='git commit -m'
alias gc='git clone'
alias gco='git checkout'
alias gb='git branch'
alias bp='atom ~/.bash_profile'
alias be='bundle exec'
alias gg='git graph'
alias gpr='git pull --rebase'
alias rdbm='rake db:migrate'
